#!/bin/bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew install neofetch cask ; 
brew cask install google-chrome steam ; 
brew update&
clear
curl -A 'foo' https://raw.githubusercontent.com/Risingfeanyx/dotfiles/master/Mac_Bashrc >> .bashrc
